# Generated by Django 5.2.2 on 2025-06-15 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, help_text='Whether this message has been edited'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='When the message was last edited', null=True),
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='History ID')),
                ('old_content', models.TextField(help_text='The previous content of the message before the edit')),
                ('edit_timestamp', models.DateTimeField(auto_now_add=True, help_text='When this edit was made')),
                ('edit_reason', models.CharField(blank=True, help_text='Optional reason for the edit', max_length=200, null=True)),
                ('edited_by', models.ForeignKey(help_text='The user who made this edit', on_delete=django.db.models.deletion.CASCADE, related_name='message_edits', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(help_text='The message this history entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='chats.message')),
            ],
            options={
                'verbose_name': 'Message History',
                'verbose_name_plural': 'Message Histories',
                'db_table': 'message_history',
                'ordering': ['-edit_timestamp'],
            },
        ),
    ]
